# Generated by Django 5.1.2 on 2024-10-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_service_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='message',
            field=models.TextField(blank=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='application',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number'),
        ),
    ]
