# Generated by Django 5.1.2 on 2024-10-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_contactdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='number',
            field=models.IntegerField(null=True, verbose_name='Number'),
        ),
    ]
