# Generated by Django 5.1.2 on 2024-10-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_application_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='application',
            name='time_of_death',
            field=models.TimeField(blank=True, null=True, verbose_name='Time of Death'),
        ),
    ]
