# Generated by Django 5.1.2 on 2024-10-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_application_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Social name')),
                ('icon', models.CharField(max_length=100, verbose_name='Font Awesome Icon')),
                ('link', models.TextField(verbose_name='link')),
            ],
        ),
    ]
